In [8]:
import pandas as pd

df = pd.read_csv("employee_scaling_practice.csv")
df

# Min-Max normalization converts values into a fixed range, usually, 0 to 1

  Employee  Age  Experience  Salary
0     Amit   25           2   30000
1     Neha   30           5   60000
2      Raj   40          10  100000
3    Priya   50          15  150000
4    Karan   60          20  200000
5     Riya   35           7   80000
6   Vishal   45          12  120000

In [9]:
#                      Z-Score vs Min-Max

# This is the part you should remember for your exam/interview.

# 	                 Z-Score	                              Min-Max
# Main idea        Distance from average	          Convert to fixed range
# Formula	         (X - mean) / std	                (X-min)/(max-min)
# Typical          range	No fixed range	              Usually 0 to 1
# Center	        Mean becomes approximately 0	      Minimum becomes 0
# Maximum	         No fixed maximum	                Maximum becomes 1
# Output example 	 -1.14, 0.61, 1.34                    	0, 0.35, 1



# Z-score → "How far from average?"

# Min-Max → "Where does this value lie between minimum and maximum?"

In [10]:
#                   Min-Maz Normalization

# Minimum Salary
min_salary = df["Salary"].min()

# Maximum Salary
max_salary = df["Salary"].max()


# Min-Maz Normalization
df["Salary_minmax"] = round(((df["Salary"] - min_salary)/(max_salary - min_salary) ), 2)

df

  Employee  Age  Experience  Salary  Salary_minmax
0     Amit   25           2   30000           0.00
1     Neha   30           5   60000           0.18
2      Raj   40          10  100000           0.41
3    Priya   50          15  150000           0.71
4    Karan   60          20  200000           1.00
5     Riya   35           7   80000           0.29
6   Vishal   45          12  120000           0.53