In [25]:
import pandas as pd

df = pd.read_csv("case3_hospital_appointments_raw.csv")
df["Age"]

# 1. Sort appointments by Fee from highest to lowest.
# 2. Display the five highest-fee appointments.
# 3. Sort first by Department and then by Rating from highest to lowest within each department.
# 4. Find the five oldest patients.
# 5. Sort appointments by Appointment_Date from earliest to latest.
# 6. Display the three highest-rated appointments.

0               45
1     thirty eight
2               29
3              NaN
4               34
5               52
6               41
7               60
8               27
9              48
10              31
11              55
12              29
13             48
14              36
15              43
16              50
17              26
18              39
19              47
Name: Age, dtype: object

In [26]:
df_clean = df.copy()

df_clean["Age"] = pd.to_numeric(df_clean["Age"], errors = "coerce")
df_clean

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45.0,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,NaN,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29.0,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34.0,bad date,14:00,800,Pending,Yes,Not Rated
5,A006,Arjun Rao,Orthopedics,Surat,52.0,14-08-2026,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41.0,14/08/2026,10:45,NaN,Paid,TRUE,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60.0,15-08-2026,11:30,1200,Cancelled,FALSE,3.9
8,A009,Kavya Nair,ENT,Surat,27.0,15/08/2026,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48.0,16-08-2026,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31.0,16/08/2026,10:30,900,Paid,Y,4.8
11,A012,Kabir Khan,Cardiology,Surat,55.0,17-08-2026,12:00,1200,Paid,N,4.4
12,A003,Diya Mehta,Dermatology,Surat,29.0,13-08-2026,11:00,900,Paid,Y,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48.0,16-08-2026,09:45,1500,Pending,No,4.1
14,A013,Sara Modi,ENT,Vadodara,36.0,17/08/2026,15:15,800,Paid,Yes,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43.0,18-08-2026,09:15,1200,Pending,No,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50.0,18/08/2026,11:45,1500,Paid,TRUE,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26.0,19-08-2026,13:30,900,Cancelled,FALSE,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39.0,19/08/2026,14:30,800,Paid,Yes,4.5
19,A018,Om Joshi,Cardiology,Surat,47.0,20-08-2026,10:00,1200,Paid,No,4.6

In [27]:
df_clean["Appointment_Date"] = pd.to_datetime(df_clean["Appointment_Date"], format="mixed", errors='coerce', dayfirst = True)
df_clean

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45.0,2026-08-12,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,NaN,2026-08-12,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,2026-08-13,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34.0,NaT,14:00,800,Pending,Yes,Not Rated
5,A006,Arjun Rao,Orthopedics,Surat,52.0,2026-08-14,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41.0,2026-08-14,10:45,NaN,Paid,TRUE,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60.0,2026-08-15,11:30,1200,Cancelled,FALSE,3.9
8,A009,Kavya Nair,ENT,Surat,27.0,2026-08-15,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31.0,2026-08-16,10:30,900,Paid,Y,4.8
11,A012,Kabir Khan,Cardiology,Surat,55.0,2026-08-17,12:00,1200,Paid,N,4.4
12,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Y,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
14,A013,Sara Modi,ENT,Vadodara,36.0,2026-08-17,15:15,800,Paid,Yes,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43.0,2026-08-18,09:15,1200,Pending,No,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50.0,2026-08-18,11:45,1500,Paid,TRUE,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26.0,2026-08-19,13:30,900,Cancelled,FALSE,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39.0,2026-08-19,14:30,800,Paid,Yes,4.5
19,A018,Om Joshi,Cardiology,Surat,47.0,2026-08-20,10:00,1200,Paid,No,4.6

In [28]:
df_clean["Rating"] = pd.to_numeric(df_clean["Rating"], errors = "coerce")
df_clean

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45.0,2026-08-12,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,NaN,2026-08-12,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,2026-08-13,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34.0,NaT,14:00,800,Pending,Yes,NaN
5,A006,Arjun Rao,Orthopedics,Surat,52.0,2026-08-14,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41.0,2026-08-14,10:45,NaN,Paid,TRUE,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60.0,2026-08-15,11:30,1200,Cancelled,FALSE,3.9
8,A009,Kavya Nair,ENT,Surat,27.0,2026-08-15,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31.0,2026-08-16,10:30,900,Paid,Y,4.8
11,A012,Kabir Khan,Cardiology,Surat,55.0,2026-08-17,12:00,1200,Paid,N,4.4
12,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Y,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
14,A013,Sara Modi,ENT,Vadodara,36.0,2026-08-17,15:15,800,Paid,Yes,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43.0,2026-08-18,09:15,1200,Pending,No,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50.0,2026-08-18,11:45,1500,Paid,TRUE,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26.0,2026-08-19,13:30,900,Cancelled,FALSE,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39.0,2026-08-19,14:30,800,Paid,Yes,4.5
19,A018,Om Joshi,Cardiology,Surat,47.0,2026-08-20,10:00,1200,Paid,No,4.6

In [37]:
df_clean["Insurance"] = df_clean["Insurance"].replace({"Y": "Yes", "TRUE":"Yes", "FALSE":"NO", "N":"No" })
df_clean["Appointment_ID"] = df_clean["Appointment_ID"].drop_duplicates().reset_index(drop=True)
df_clean

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45.0,2026-08-12,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,NaN,2026-08-12,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Yes,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,2026-08-13,12:30,1200,Paid,No,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34.0,NaT,14:00,800,Pending,Yes,NaN
5,A006,Arjun Rao,Orthopedics,Surat,52.0,2026-08-14,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41.0,2026-08-14,10:45,NaN,Paid,Yes,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60.0,2026-08-15,11:30,1200,Cancelled,NO,3.9
8,A009,Kavya Nair,ENT,Surat,27.0,2026-08-15,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31.0,2026-08-16,10:30,900,Paid,Yes,4.8
11,A012,Kabir Khan,Cardiology,Surat,55.0,2026-08-17,12:00,1200,Paid,No,4.4
12,NaN,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Yes,4.6
13,A013,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
14,A014,Sara Modi,ENT,Vadodara,36.0,2026-08-17,15:15,800,Paid,Yes,4.7
15,A015,Dev Shah,Cardiology,Ahmedabad,43.0,2026-08-18,09:15,1200,Pending,No,4.0
16,A016,Riya Kapoor,Orthopedics,Surat,50.0,2026-08-18,11:45,1500,Paid,Yes,4.9
17,A017,Yash Patel,Dermatology,Vadodara,26.0,2026-08-19,13:30,900,Cancelled,NO,3.8
18,A018,Tara Mehta,ENT,Ahmedabad,39.0,2026-08-19,14:30,800,Paid,Yes,4.5
19,NaN,Om Joshi,Cardiology,Surat,47.0,2026-08-20,10:00,1200,Paid,No,4.6

In [38]:
df_clean["Patient_Name"] = df_clean["Patient_Name"].drop_duplicates().reset_index(drop=True)
df_clean

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45.0,2026-08-12,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,NaN,2026-08-12,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Yes,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,2026-08-13,12:30,1200,Paid,No,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34.0,NaT,14:00,800,Pending,Yes,NaN
5,A006,Arjun Rao,Orthopedics,Surat,52.0,2026-08-14,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41.0,2026-08-14,10:45,NaN,Paid,Yes,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60.0,2026-08-15,11:30,1200,Cancelled,NO,3.9
8,A009,Kavya Nair,ENT,Surat,27.0,2026-08-15,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31.0,2026-08-16,10:30,900,Paid,Yes,4.8
11,A012,Kabir Khan,Cardiology,Surat,55.0,2026-08-17,12:00,1200,Paid,No,4.4
12,NaN,Sara Modi,Dermatology,Surat,29.0,2026-08-13,11:00,900,Paid,Yes,4.6
13,A013,Dev Shah,Orthopedics,Vadodara,48.0,2026-08-16,09:45,1500,Pending,No,4.1
14,A014,Riya Kapoor,ENT,Vadodara,36.0,2026-08-17,15:15,800,Paid,Yes,4.7
15,A015,Yash Patel,Cardiology,Ahmedabad,43.0,2026-08-18,09:15,1200,Pending,No,4.0
16,A016,Tara Mehta,Orthopedics,Surat,50.0,2026-08-18,11:45,1500,Paid,Yes,4.9
17,A017,Om Joshi,Dermatology,Vadodara,26.0,2026-08-19,13:30,900,Cancelled,NO,3.8
18,A018,NaN,ENT,Ahmedabad,39.0,2026-08-19,14:30,800,Paid,Yes,4.5
19,NaN,NaN,Cardiology,Surat,47.0,2026-08-20,10:00,1200,Paid,No,4.6