In [14]:
import pandas as pd

df = pd.DataFrame({
    "Employee_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112],
    "Name": ["Amit", "Neha", "Rahul", "Priya", "Karan", "Diya",
             "Rohan", "Meera", "Arjun", "Kavya", "Jay", "Isha"],
    "Department": ["IT", "HR", "IT", "Sales", "HR", "IT",
                   "Sales", "IT", "Finance", "Sales", "Finance", "HR"],
    "Experience": [2, 5, 3, 7, 4, 1, 6, 8, 5, 2, 9, 3],
    "Salary": [35000, 45000, 40000, 60000, 42000, 30000,
               55000, 75000, 65000, 38000, 85000, 37000],
    "Performance": ["Good", "Average", "Excellent", "Good", "Average",
                    "Good", "Excellent", "Excellent", "Good", "Average",
                    "Excellent", "Good"],
    "Joining_Date": ["2022-01-15", "2020-06-10", "2021-03-20",
                     "2019-08-12", "2021-11-05", "2023-02-18",
                     "2020-09-25", "2018-04-16", "2019-12-01",
                     "2022-07-11", "2017-05-08", "2021-06-22"]
})

df

    Employee_ID   Name Department  Experience  Salary Performance Joining_Date
0           101   Amit         IT           2   35000        Good   2022-01-15
1           102   Neha         HR           5   45000     Average   2020-06-10
2           103  Rahul         IT           3   40000   Excellent   2021-03-20
3           104  Priya      Sales           7   60000        Good   2019-08-12
4           105  Karan         HR           4   42000     Average   2021-11-05
5           106   Diya         IT           1   30000        Good   2023-02-18
6           107  Rohan      Sales           6   55000   Excellent   2020-09-25
7           108  Meera         IT           8   75000   Excellent   2018-04-16
8           109  Arjun    Finance           5   65000        Good   2019-12-01
9           110  Kavya      Sales           2   38000     Average   2022-07-11
10          111    Jay    Finance           9   85000   Excellent   2017-05-08
11          112   Isha         HR           3   37000        Good   2021-06-22

In [15]:
# initial inspection
print(df.head()) #first 5 rows
print(df.shape) # shows rows, columns
print(df.dtypes) #shows datatype of each columns
# print(df.info()) #shows columns and their data types
print(df.isnull().sum()) #count the number of null values fro  each column
df.describe() #Gives statistical information about numerical columns

   Employee_ID   Name Department  Experience  Salary Performance Joining_Date
0          101   Amit         IT           2   35000        Good   2022-01-15
1          102   Neha         HR           5   45000     Average   2020-06-10
2          103  Rahul         IT           3   40000   Excellent   2021-03-20
3          104  Priya      Sales           7   60000        Good   2019-08-12
4          105  Karan         HR           4   42000     Average   2021-11-05
(12, 7)
Employee_ID      int64
Name            object
Department      object
Experience       int64
Salary           int64
Performance     object
Joining_Date    object
dtype: object
Employee_ID     0
Name            0
Department      0
Experience      0
Salary          0
Performance     0
Joining_Date    0
dtype: int64

       Employee_ID  Experience        Salary
count    12.000000   12.000000     12.000000
mean    106.500000    4.583333  50583.333333
std       3.605551    2.539088  17380.544679
min     101.000000    1.000000  30000.000000
25%     103.750000    2.750000  37750.000000
50%     106.500000    4.500000  43500.000000
75%     109.250000    6.250000  61250.000000
max     112.000000    9.000000  85000.000000

In [16]:
# Find the average salary of all employees.
print(df["Salary"].mean())

50583.333333333336

In [17]:
# Find the highest-paid employee.
print(df["Salary"].max())

85000

In [18]:
# Count employees in each department.
print(df.groupby("Department")["Employee_ID"].count())

Department
Finance    2
HR         3
IT         4
Sales      3
Name: Employee_ID, dtype: int64

In [19]:
# Calculate the average salary department-wise.
print(df.groupby("Department")["Salary"].mean())

Department
Finance    75000.000000
HR         41333.333333
IT         45000.000000
Sales      51000.000000
Name: Salary, dtype: float64

In [20]:
# Find employees with more than 4 years of experience.
print(df[df["Experience"] > 4])

    Employee_ID   Name Department  Experience  Salary Performance Joining_Date
1           102   Neha         HR           5   45000     Average   2020-06-10
3           104  Priya      Sales           7   60000        Good   2019-08-12
6           107  Rohan      Sales           6   55000   Excellent   2020-09-25
7           108  Meera         IT           8   75000   Excellent   2018-04-16
8           109  Arjun    Finance           5   65000        Good   2019-12-01
10          111    Jay    Finance           9   85000   Excellent   2017-05-08

In [21]:
# Sort employees by salary from highest to lowest.
print(df.sort_values(by="Salary" ,ascending=False))

    Employee_ID   Name Department  Experience  Salary Performance Joining_Date
10          111    Jay    Finance           9   85000   Excellent   2017-05-08
7           108  Meera         IT           8   75000   Excellent   2018-04-16
8           109  Arjun    Finance           5   65000        Good   2019-12-01
3           104  Priya      Sales           7   60000        Good   2019-08-12
6           107  Rohan      Sales           6   55000   Excellent   2020-09-25
1           102   Neha         HR           5   45000     Average   2020-06-10
4           105  Karan         HR           4   42000     Average   2021-11-05
2           103  Rahul         IT           3   40000   Excellent   2021-03-20
9           110  Kavya      Sales           2   38000     Average   2022-07-11
11          112   Isha         HR           3   37000        Good   2021-06-22
0           101   Amit         IT           2   35000        Good   2022-01-15
5           106   Diya         IT           1   30000        Good   2023-02-18

In [25]:
# Find the department with the highest average salary.
df.groupby("Department")["Salary"].mean().max()

np.float64(75000.0)

In [26]:
# Calculate the total salary expenditure for each department.
print(df.groupby("Department")["Salary"].sum())

Department
Finance    150000
HR         124000
IT         180000
Sales      153000
Name: Salary, dtype: int64

In [31]:
# Convert Joining_Date to datetime and find employees who joined after January 1, 2021.

df["Joining_Date"] = pd.to_datetime(df["Joining_Date"], errors='coerce', dayfirst=True, format='mixed')

df[ df["Joining_Date"] > '2021-01-01']

    Employee_ID   Name Department  Experience  Salary Performance Joining_Date
0           101   Amit         IT           2   35000        Good   2022-01-15
2           103  Rahul         IT           3   40000   Excellent   2021-03-20
4           105  Karan         HR           4   42000     Average   2021-11-05
5           106   Diya         IT           1   30000        Good   2023-02-18
9           110  Kavya      Sales           2   38000     Average   2022-07-11
11          112   Isha         HR           3   37000        Good   2021-06-22