In [1]:
import pandas as pd

# Hospital Patient Records
data = {
    "Patient": [" karan ", "Riya", "Amit", "Riya", "Neha", "Amit", "Jay"],
    "Age": ["22", "30", None, "30", "45", "150", "25"],
    "Department": ["cardiology", "ENT", "ENT", "ENT", "Dental", "dental ", "ENT"],
    "Bill": ["1500", "2000", "1800", "2000", None, "2500", "1200"],
    "Visit_Date": ["01-10-2026", "02-10-2026", "03-10-2026", "02-10-2026", "invalid", "05-10-2026", "06-10-2026"]
}

df = pd.DataFrame(data)
df

   Patient   Age  Department  Bill  Visit_Date
0   karan     22  cardiology  1500  01-10-2026
1     Riya    30         ENT  2000  02-10-2026
2     Amit  None         ENT  1800  03-10-2026
3     Riya    30         ENT  2000  02-10-2026
4     Neha    45      Dental  None     invalid
5     Amit   150     dental   2500  05-10-2026
6      Jay    25         ENT  1200  06-10-2026

In [8]:
# inspect the data
print(df.dtypes)
print(df.info())
print(df.isnull().sum())

Patient       object
Age           object
Department    object
Bill          object
Visit_Date    object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Patient     7 non-null      object
 1   Age         6 non-null      object
 2   Department  7 non-null      object
 3   Bill        6 non-null      object
 4   Visit_Date  7 non-null      object
dtypes: object(5)
memory usage: 412.0+ bytes
None
Patient       0
Age           1
Department    0
Bill          1
Visit_Date    0
dtype: int64

In [ ]:
# Removed space and make the first letter in UpperCase
df["Patient"] = df["Patient"].str.strip().str.title()
df

  Patient   Age  Department  Bill  Visit_Date
0   Karan    22  cardiology  1500  01-10-2026
1    Riya    30         ENT  2000  02-10-2026
2    Amit  None         ENT  1800  03-10-2026
3    Riya    30         ENT  2000  02-10-2026
4    Neha    45      Dental  None     invalid
5    Amit   150     dental   2500  05-10-2026
6     Jay    25         ENT  1200  06-10-2026