In [115]:
import pandas as pd

df = pd.read_csv("case3_hospital_appointments_raw.csv")

#                     Part A - Initial Inspection

# 1. Load the CSV into df. Display the first 10 rows, shape, columns, dtypes, and info().
#                   columnss to clean
# Age, Appointment_Date, Fee ,Insurance, Rating

print(df.head(10))
print(df.shape) #rows
print(df.columns) #columns
print(df.info())
print(df.dtypes)


# 2. Identify at least five data-quality or data-type problems visible in the file.

# problem 1 -> Age = thirty eight
# problem 2 -> Age = NaN
# problem 3 -> Fee = 1,500
# probelm 4 -> Appointment Date = mixed date formats(13-08-2026 & 13/08/2026) also bad date
# Problem 5 -> Insurance  = (Y, N, TRUE, FALSE)
# Problem 6 -> Rating = Not Rated
# Problem 7 -> Appointment_ID  = A010 and A003 are duplicated

# 3. Create a working copy named df_clean.
df_clean = df.copy()
df_clean

  Appointment_ID   Patient_Name   Department       City           Age  \
0           A001   Meera Patel    Cardiology   Vadodara            45
1           A002     Rohan Shah  Orthopedics  Ahmedabad  thirty eight
2           A003     Diya Mehta  Dermatology      Surat            29
3           A004    Aarav Desai   Cardiology   Vadodara           NaN
4           A005    Priya Joshi          ENT  Ahmedabad            34
5           A006      Arjun Rao  Orthopedics      Surat            52
6           A007   Neha Trivedi  Dermatology   Vadodara            41
7           A008     Vivek Iyer   Cardiology  Ahmedabad            60
8           A009     Kavya Nair          ENT      Surat            27
9           A010    Rahul Verma  Orthopedics   Vadodara           48

  Appointment_Date   Time    Fee Payment_Status Insurance     Rating
0       12-08-2026  09:30   1200           Paid       Yes        4.8
1       12/08/2026  10:15   1500        Pending        No        4.2
2       13-08-2026  11:00   900            Paid         Y        4.6
3       13/08/2026  12:30   1200           Paid         N        4.5
4         bad date  14:00    800        Pending       Yes  Not Rated
5       14-08-2026  09:00  1,500           Paid        No        4.7
6       14/08/2026  10:45    NaN           Paid      TRUE        4.3
7       15-08-2026  11:30   1200      Cancelled     FALSE        3.9
8       15/08/2026  13:00    800           Paid       Yes        4.9
9       16-08-2026  09:45   1500        Pending        No        4.1
(20, 11)
Index(['Appointment_ID', 'Patient_Name', 'Department', 'City', 'Age',
       'Appointment_Date', 'Time', 'Fee', 'Payment_Status', 'Insurance',
       'Rating'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Appointment_ID    20 non-null     object
 1   Patient_Name      20 non-null     object
 2   Department        20 non-null     object
 3   City              20 non-null     object
 4   Age               19 non-null     object
 5   Appointment_Date  20 non-null     object
 6   Time              20 non-null     object
 7   Fee               19 non-null     object
 8   Payment_Status    20 non-null     object
 9   Insurance         20 non-null     object
 10  Rating            20 non-null     object
dtypes: object(11)
memory usage: 1.8+ KB
None
Appointment_ID      object
Patient_Name        object
Department          object
City                object
Age                 object
Appointment_Date    object
Time                object
Fee                 object
Payment_Status      object
Insurance           object
Rating              object
dtype: object

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,12-08-2026,09:30,1200,Paid,Yes,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,thirty eight,12/08/2026,10:15,1500,Pending,No,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,NaN,13/08/2026,12:30,1200,Paid,N,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,bad date,14:00,800,Pending,Yes,Not Rated
5,A006,Arjun Rao,Orthopedics,Surat,52,14-08-2026,09:00,"1,500",Paid,No,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41,14/08/2026,10:45,NaN,Paid,TRUE,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60,15-08-2026,11:30,1200,Cancelled,FALSE,3.9
8,A009,Kavya Nair,ENT,Surat,27,15/08/2026,13:00,800,Paid,Yes,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48,16-08-2026,09:45,1500,Pending,No,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31,16/08/2026,10:30,900,Paid,Y,4.8
11,A012,Kabir Khan,Cardiology,Surat,55,17-08-2026,12:00,1200,Paid,N,4.4
12,A003,Diya Mehta,Dermatology,Surat,29,13-08-2026,11:00,900,Paid,Y,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48,16-08-2026,09:45,1500,Pending,No,4.1
14,A013,Sara Modi,ENT,Vadodara,36,17/08/2026,15:15,800,Paid,Yes,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43,18-08-2026,09:15,1200,Pending,No,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50,18/08/2026,11:45,1500,Paid,TRUE,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26,19-08-2026,13:30,900,Cancelled,FALSE,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39,19/08/2026,14:30,800,Paid,Yes,4.5
19,A018,Om Joshi,Cardiology,Surat,47,20-08-2026,10:00,1200,Paid,No,4.6

In [116]:
# Part B - Chapter 5: Data Type Conversion
# 1. Remove leading/trailing spaces from Patient_Name.

df_clean["Patient_Name"] = df_clean["Patient_Name"].str.strip()
# for i in df_clean["Patient_Name"]:
#   print(repr(i))

# 2. Convert Age safely to a nullable integer. Invalid age text must become missing.
df_clean["Age"] = pd.to_numeric(df_clean["Age"], errors='coerce')
df_clean["Age"] = df_clean["Age"].astype("Int64")
df_clean["Age"]

# 3. Clean Fee values containing commas/spaces and convert Fee to numeric.
df_clean["Fee"] = df_clean["Fee"].str.strip()
df_clean["Fee"] = df_clean["Fee"].str.replace(",", "")
df_clean["Fee"] = pd.to_numeric(df_clean["Fee"], errors='coerce')
df_clean["Fee"]
# 4. Convert Appointment_Date to datetime using the mixed day-first formats. Invalid dates should become NaT.
df_clean["Appointment_Date"] = pd.to_datetime(df_clean["Appointment_Date"], errors='coerce', format="mixed", dayfirst=True)
df_clean["Appointment_Date"]

# 5. Standardize Insurance values (Yes/Y/TRUE and No/N/FALSE) and convert them to nullable Boolean.
df_clean["Insurance"] = df_clean["Insurance"].replace({
  "Y": "Yes", "N": "No", "TRUE":"Yes", "FALSE": "No"
}).replace({
  "Yes": True, "No": False
}).astype("boolean")

df_clean["Insurance"]

# 6. Convert Rating to numeric safely.
df_clean["Rating"] = pd.to_numeric(df_clean["Rating"], errors='coerce')
df_clean["Rating"]

# 7. Convert Department, City, and Payment_Status to category dtype.
df_clean["Department"] = df_clean["Department"].astype("category")
df_clean["City"] = df_clean["City"].astype("category")
df_clean["Payment_Status"] = df_clean["Payment_Status"].astype("category")
# 8. Display the final dtypes after conversion and identify all conversion-created missing values.
df_clean.dtypes
df_clean

C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\150621066.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  }).replace({

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,2026-08-12,09:30,1200.0,Paid,True,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,<NA>,2026-08-12,10:15,1500.0,Pending,False,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,2026-08-13,11:00,900.0,Paid,True,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,<NA>,2026-08-13,12:30,1200.0,Paid,False,4.5
4,A005,Priya Joshi,ENT,Ahmedabad,34,NaT,14:00,800.0,Pending,True,NaN
5,A006,Arjun Rao,Orthopedics,Surat,52,2026-08-14,09:00,1500.0,Paid,False,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41,2026-08-14,10:45,NaN,Paid,True,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60,2026-08-15,11:30,1200.0,Cancelled,False,3.9
8,A009,Kavya Nair,ENT,Surat,27,2026-08-15,13:00,800.0,Paid,True,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48,2026-08-16,09:45,1500.0,Pending,False,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31,2026-08-16,10:30,900.0,Paid,True,4.8
11,A012,Kabir Khan,Cardiology,Surat,55,2026-08-17,12:00,1200.0,Paid,False,4.4
12,A003,Diya Mehta,Dermatology,Surat,29,2026-08-13,11:00,900.0,Paid,True,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48,2026-08-16,09:45,1500.0,Pending,False,4.1
14,A013,Sara Modi,ENT,Vadodara,36,2026-08-17,15:15,800.0,Paid,True,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43,2026-08-18,09:15,1200.0,Pending,False,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50,2026-08-18,11:45,1500.0,Paid,True,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26,2026-08-19,13:30,900.0,Cancelled,False,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39,2026-08-19,14:30,800.0,Paid,True,4.5
19,A018,Om Joshi,Cardiology,Surat,47,2026-08-20,10:00,1200.0,Paid,False,4.6

In [117]:
#                 Part C - Chapter 3: Missing Values

# 1. Count missing values after conversion.
df_clean.isna().sum() #total 5 missing values

# 2. Display every row containing at least one missing value.
df_clean[
  df_clean["Age"].isna() |
  df_clean["Appointment_Date"].isna() |
  df_clean["Fee"].isna() |
  df_clean["Rating"].isna()
]

# 3. Fill missing Age with the median Age.
median_age = df_clean["Age"].median()
median_age
df_clean["Age"] = df_clean["Age"].fillna(median_age)
df_clean["Age"]

# 4. Fill missing Fee using the median Fee of the corresponding Department.
df_clean["Fee"] = df_clean.groupby("Department")["Fee"].transform(lambda x: x.fillna(x.median()))
df_clean["Fee"]

# 5. Fill missing Rating using the median Rating of the corresponding Department.
df_clean["Rating"] = df_clean.groupby("Department")["Rating"].transform(lambda x: x.fillna(x.median()))

# 6. The appointment with an invalid Appointment_Date cannot be used for date-based scheduling analysis. Remove that row.
df_clean = df_clean.dropna(subset=["Appointment_Date"])
df_clean

# 7. Verify that the remaining dataset has no missing values in Age, Fee, Rating, or Appointment_Date.
df_clean[["Age", "Appointment_Date", "Rating", "Fee"]].isna().sum()

df_clean

C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\477936818.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean["Fee"] = df_clean.groupby("Department")["Fee"].transform(lambda x: x.fillna(x.median()))
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\477936818.py:25: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean["Rating"] = df_clean.groupby("Department")["Rating"].transform(lambda x: x.fillna(x.median()))

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
0,A001,Meera Patel,Cardiology,Vadodara,45,2026-08-12,09:30,1200.0,Paid,True,4.8
1,A002,Rohan Shah,Orthopedics,Ahmedabad,42,2026-08-12,10:15,1500.0,Pending,False,4.2
2,A003,Diya Mehta,Dermatology,Surat,29,2026-08-13,11:00,900.0,Paid,True,4.6
3,A004,Aarav Desai,Cardiology,Vadodara,42,2026-08-13,12:30,1200.0,Paid,False,4.5
5,A006,Arjun Rao,Orthopedics,Surat,52,2026-08-14,09:00,1500.0,Paid,False,4.7
6,A007,Neha Trivedi,Dermatology,Vadodara,41,2026-08-14,10:45,900.0,Paid,True,4.3
7,A008,Vivek Iyer,Cardiology,Ahmedabad,60,2026-08-15,11:30,1200.0,Cancelled,False,3.9
8,A009,Kavya Nair,ENT,Surat,27,2026-08-15,13:00,800.0,Paid,True,4.9
9,A010,Rahul Verma,Orthopedics,Vadodara,48,2026-08-16,09:45,1500.0,Pending,False,4.1
10,A011,Anaya Singh,Dermatology,Ahmedabad,31,2026-08-16,10:30,900.0,Paid,True,4.8
11,A012,Kabir Khan,Cardiology,Surat,55,2026-08-17,12:00,1200.0,Paid,False,4.4
12,A003,Diya Mehta,Dermatology,Surat,29,2026-08-13,11:00,900.0,Paid,True,4.6
13,A010,Rahul Verma,Orthopedics,Vadodara,48,2026-08-16,09:45,1500.0,Pending,False,4.1
14,A013,Sara Modi,ENT,Vadodara,36,2026-08-17,15:15,800.0,Paid,True,4.7
15,A014,Dev Shah,Cardiology,Ahmedabad,43,2026-08-18,09:15,1200.0,Pending,False,4.0
16,A015,Riya Kapoor,Orthopedics,Surat,50,2026-08-18,11:45,1500.0,Paid,True,4.9
17,A016,Yash Patel,Dermatology,Vadodara,26,2026-08-19,13:30,900.0,Cancelled,False,3.8
18,A017,Tara Mehta,ENT,Ahmedabad,39,2026-08-19,14:30,800.0,Paid,True,4.5
19,A018,Om Joshi,Cardiology,Surat,47,2026-08-20,10:00,1200.0,Paid,False,4.6

In [118]:
# Part D - Chapter 4: Duplicate Handling

# 1. Count later exact duplicate rows
df_clean.duplicated().sum()


# 2. Display all rows involved in exact duplicate groups
df_clean[df_clean.duplicated(keep=False)]


# 3. Check repeated Appointment_ID values
# A003 and A010


# 4. Remove confirmed exact duplicates and reset the index
df_clean = df_clean.drop_duplicates().reset_index(drop=True)

df_clean


# 5. Verify that no exact duplicates remain and report final row count
print("Duplicates remaining:", df_clean.duplicated().sum())
print("Final row count:", len(df_clean))
print("Index: ", df_clean.index)
print(df_clean.shape)
print(df_clean["Appointment_ID"].value_counts())

Duplicates remaining: 0
Final row count: 17
Index:  RangeIndex(start=0, stop=17, step=1)
(17, 11)
Appointment_ID
A001    1
A002    1
A003    1
A004    1
A006    1
A007    1
A008    1
A009    1
A010    1
A011    1
A012    1
A013    1
A014    1
A015    1
A016    1
A017    1
A018    1
Name: count, dtype: int64

In [119]:
# Part E - Chapter 1: Sorting
# 1. Sort appointments by Fee from highest to lowest.
df_clean = df_clean.sort_values(by="Fee", ascending=False)
df_clean

# 2. Display the five highest-fee appointments.
df_clean.head(5)
# 3. Sort first by Department and then by (Rating from highest to lowest) within each department.
# Department → ascending (A → Z)
# Rating → descending (highest → lowest)

df_clean = df_clean.sort_values(by=["Department", "Rating"], ascending=[True, False])
df_clean
# 4. Find the five oldest patients.
df_clean.sort_values(by="Age", ascending=False).head(5)
# 5. Sort appointments by Appointment_Date from earliest to latest.
df_clean.sort_values(by="Appointment_Date")
# 6. Display the three highest-rated appointments.
df_clean.sort_values(by="Rating", ascending=False).head(3)

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
13,A015,Riya Kapoor,Orthopedics,Surat,50,2026-08-18,11:45,1500.0,Paid,True,4.9
7,A009,Kavya Nair,ENT,Surat,27,2026-08-15,13:00,800.0,Paid,True,4.9
0,A001,Meera Patel,Cardiology,Vadodara,45,2026-08-12,09:30,1200.0,Paid,True,4.8

In [120]:
# Part F -        Chapter 2: Grouping
# 1. Count appointments by Department
df_clean.groupby("Department")["Appointment_ID"].count()
# 2. Calculate total Fee by Department.
df_clean.groupby("Department")["Fee"].sum()
# 3. Calculate average Fee by City.
df_clean.groupby("City")["Fee"].mean()
# 4. Calculate average Rating by Department.
df_clean.groupby("Department")["Rating"].mean()
# 5. Find minimum, maximum, and average Age by Department.
# print("\t\tMinimum: \n", df_clean.groupby("Department")["Age"].min())
# print("\t\tMaximum: \n", df_clean.groupby("Department")["Age"].max())
# print("\t\tAverage: \n", df_clean.groupby("Department")["Age"].mean())

# 6. Count appointments by Payment_Status.
df_clean.groupby("Payment_Status")["Appointment_ID"].count()

# 7. Group by City and Department and calculate total Fee.
df_clean.groupby(by=["City", "Department"])["Fee"].sum()

# 8. Find the department with the highest total Fee.
df_clean.groupby("Department")["Fee"].sum().sort_values(ascending=False).head(1)
# Orthopedics    1500.0
# 9. Find the city with the highest average Rating.
df_clean.groupby("City")["Rating"].mean().sort_values(ascending=False).head(1)

C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Appointment_ID"].count()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Fee"].sum()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("City")["Fee"].mean()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Rating"].mean()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:16: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Payment_Status")["Appointment_ID"].count()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:19: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby(by=["City", "Department"])["Fee"].sum()
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:22: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Fee"].sum().sort_values(ascending=False).head(1)
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1769461634.py:25: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("City")["Rating"].mean().sort_values(ascending=False).head(1)

City
Surat    4.683333
Name: Rating, dtype: float64

In [121]:
# Part G - Management Questions
# 1. Which department generated the highest total fee?
df_clean.groupby("Department")["Fee"].sum().sort_values(ascending=False).head(1)
# cardiology - 7200

# 2. Which department has the highest average patient rating?
df_clean.groupby("Department")["Rating"].mean().sort_values(ascending=False).head(1)
# ENT -  4.700000

# 3. Which city has the largest number of valid appointments?
df_clean.groupby("City")["Appointment_ID"].count().sort_values(ascending=False).head(1)
# Surat 6 and Vadodra also 6

# 4. What percentage of cleaned appointments use Insurance? (Hint: Boolean True can be counted.)
df_clean["Insurance"].mean() * 100
# 47.058
# 5. Which payment status is most common?
df_clean["Payment_Status"].value_counts().head(1)
# Paid    12
# 6. Which department has the oldest average patient age?
df_clean.groupby("Department")["Age"].mean().sort_values(ascending=False).head(1)
# Cardiology    48.666667

# 7. Identify the highest-rated valid appointment and its patient, department, and city.
df_clean[df_clean["Rating"] == df_clean["Rating"].max()]
# A015	Riya Kapoor	Orthopedics

# 8. Write three short management observations based on your grouped and sorted results.
# 1.  Cardiology generated the highest total fee
# 2. ENT had the highest average patient rating
# 3.Paid appointments were the most common payment status,

C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1005734132.py:3: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Fee"].sum().sort_values(ascending=False).head(1)
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1005734132.py:7: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Rating"].mean().sort_values(ascending=False).head(1)
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1005734132.py:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("City")["Appointment_ID"].count().sort_values(ascending=False).head(1)
C:\Users\KARAN\AppData\Local\Temp\ipykernel_11356\1005734132.py:21: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_clean.groupby("Department")["Age"].mean().sort_values(ascending=False).head(1)

,Appointment_ID,Patient_Name,Department,City,Age,Appointment_Date,Time,Fee,Payment_Status,Insurance,Rating
7,A009,Kavya Nair,ENT,Surat,27,2026-08-15,13:00,800.0,Paid,True,4.9
13,A015,Riya Kapoor,Orthopedics,Surat,50,2026-08-18,11:45,1500.0,Paid,True,4.9

In [125]:
# creating a clean csv
df_clean.reset_index(drop=True)
df_clean.to_csv("case3_clean.csv", index=False)