In [82]:
import pandas as pd
df = pd.read_csv("case1_student_admission_raw.csv")

In [83]:
# Part A
# Q1.Load the raw CSV into df and display the first 10 rows.
print(df.head(10))

  Student_ID     Name         Age     Marks Admission_Date Hostel  Course  \
0       S001   Aarav           19        85     12-06-2026    Yes     BCA
1       S002     Diya          20       92      13/06/2026     No     BCA
2       S003    Rohan  twenty one        78     14-06-2026    YES  BSc IT
3       S004    Priya          19    Absent     15/06/2026    yes     BCA
4       S005    Arjun          22        88   invalid date     No     MCA
5       S006     Neha         NaN        81     17-06-2026      Y  BSc IT
6       S007    Rahul          20       67      18/06/2026      N     BCA
7       S008    Kavya          21        95     19-06-2026    Yes     MCA
8       S009    Vivek          22  84 marks     20/06/2026     No     MCA
9       S010    Meera         20         76     21-06-2026    yes  BSc IT

        City  Semester
0   Vadodara         3
1  Ahmedabad         4
2      Surat         2
3   Vadodara         5
4  Ahmedabad         4
5      Surat         3
6   Vadodara         2
7  Ahmedabad         5
8      Surat         4
9   Vadodara         3

In [84]:
# 2. Check df.dtypes and df.info(). Which columns are not stored in the most useful type?
print(df.dtypes)
print(df.info())

Student_ID        object
Name              object
Age               object
Marks             object
Admission_Date    object
Hostel            object
Course            object
City              object
Semester           int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Student_ID      12 non-null     object
 1   Name            12 non-null     object
 2   Age             11 non-null     object
 3   Marks           12 non-null     object
 4   Admission_Date  12 non-null     object
 5   Hostel          12 non-null     object
 6   Course          12 non-null     object
 7   City            12 non-null     object
 8   Semester        12 non-null     int64
dtypes: int64(1), object(8)
memory usage: 996.0+ bytes
None

In [85]:
# 3. Identify the values in Age, Marks, Admission_Date, Hostel, and Semester that may cause conversion problems.
print(df["Age"].unique())
print(df["Marks"].unique())
print(df["Admission_Date"].unique())
print(df["Hostel"].unique())
print(df["Semester"].unique())

['19' '20' 'twenty one' '22' nan '21' ' 20 ']
['85' ' 92 ' '78' 'Absent' '88' '81' ' 67 ' '95' '84 marks' '76' '89' '91']
['12-06-2026' '13/06/2026' '14-06-2026' '15/06/2026' 'invalid date'
 '17-06-2026' '18/06/2026' '19-06-2026' '20/06/2026' '21-06-2026'
 '22/06/2026' '23-06-2026']
['Yes' 'No' 'YES' 'yes' 'Y' 'N' 'TRUE' 'FALSE']
[3 4 2 5]

In [86]:
# 4. Create a working copy named df_clean before making conversions.
df_clean = df.copy()
df_clean

,Student_ID,Name,Age,Marks,Admission_Date,Hostel,Course,City,Semester
0,S001,Aarav,19,85,12-06-2026,Yes,BCA,Vadodara,3
1,S002,Diya,20,92,13/06/2026,No,BCA,Ahmedabad,4
2,S003,Rohan,twenty one,78,14-06-2026,YES,BSc IT,Surat,2
3,S004,Priya,19,Absent,15/06/2026,yes,BCA,Vadodara,5
4,S005,Arjun,22,88,invalid date,No,MCA,Ahmedabad,4
5,S006,Neha,NaN,81,17-06-2026,Y,BSc IT,Surat,3
6,S007,Rahul,20,67,18/06/2026,N,BCA,Vadodara,2
7,S008,Kavya,21,95,19-06-2026,Yes,MCA,Ahmedabad,5
8,S009,Vivek,22,84 marks,20/06/2026,No,MCA,Surat,4
9,S010,Meera,20,76,21-06-2026,yes,BSc IT,Vadodara,3
10,S011,Ishaan,19,89,22/06/2026,TRUE,BCA,Ahmedabad,4
11,S012,Anaya,21,91,23-06-2026,FALSE,MCA,Surat,5

In [87]:
# Part B — Clean Text Before Conversion
# 1. Convert Name to Pandas string dtype and remove leading/trailing spaces.
df_clean["Name"] = df_clean["Name"].astype("string")
df_clean["Name"] = df_clean["Name"].str.strip()
for name in df_clean["Name"]:
  print(repr(name))

'Aarav'
'Diya'
'Rohan'
'Priya'
'Arjun'
'Neha'
'Rahul'
'Kavya'
'Vivek'
'Meera'
'Ishaan'
'Anaya'

In [88]:
# 2. Inspect the unique values in Hostel before converting it.
df_clean["Hostel"].unique()

# 3. Explain why strip() is useful before numeric or Boolean conversion.
# because it remove the unwanted spaces so that , no spaces are left in values

array(['Yes', 'No', 'YES', 'yes', 'Y', 'N', 'TRUE', 'FALSE'], dtype=object)

In [89]:
#                               Part C — Numeric Conversion
# 1. Convert Age to numeric safely. Invalid ages must become missing values rather than causing the program to stop.
df_clean["Age"] = pd.to_numeric(df_clean["Age"], errors='coerce')

# 2. Convert Marks to numeric safely.
df_clean["Marks"] = pd.to_numeric(df_clean["Marks"], errors='coerce')
# &  Identify which original values became NaN.
df_clean["Marks"].isna()


# 3. Convert Semester to a nullable integer dtype.
df_clean["Semester"] = df_clean["Semester"].astype("Int64")
df_clean["Semester"]

# 4. Convert Age to nullable Int64 after numeric conversion.
df_clean["Age"] = df_clean["Age"].astype("Int64")
df_clean["Age"]

# 5. Display Name, Age, Marks, and Semester after conversion.
df_clean[["Name", "Age", "Marks", "Semester"]]

      Name   Age  Marks  Semester
0    Aarav    19   85.0         3
1     Diya    20   92.0         4
2    Rohan  <NA>   78.0         2
3    Priya    19    NaN         5
4    Arjun    22   88.0         4
5     Neha  <NA>   81.0         3
6    Rahul    20   67.0         2
7    Kavya    21   95.0         5
8    Vivek    22    NaN         4
9    Meera    20   76.0         3
10  Ishaan    19   89.0         4
11   Anaya    21   91.0         5

In [90]:
# Part D — Date and Boolean Conversion
# 1. Convert Admission_Date to datetime. The file contains mixed day-first formats and one invalid date.
df_clean["Admission_Date"] = pd.to_datetime(df_clean["Admission_Date"], errors='coerce', format='mixed', dayfirst=True)
df_clean["Admission_Date"]

# 2. Find the row whose Admission_Date became NaT.
df_clean[df_clean["Admission_Date"].isna()]

# 3. Standardize Hostel values and convert them to Pandas nullable boolean dtype.
df_clean["Hostel"] = df_clean["Hostel"].str.strip()
df_clean["Hostel"] = df_clean["Hostel"].replace({
  "YES": "Yes", "yes": "Yes", "Y":"Yes", "N":"No", "TRUE":"Yes", "FALSE":"No"
})

df_clean["Hostel"] = df_clean["Hostel"].map({'Yes':True, "No": False}).astype("boolean")
df_clean["Hostel"]

# 4. Display Name, Admission_Date, and Hostel.
df_clean[["Name", "Admission_Date", "Hostel"]]

      Name Admission_Date  Hostel
0    Aarav     2026-06-12    True
1     Diya     2026-06-13   False
2    Rohan     2026-06-14    True
3    Priya     2026-06-15    True
4    Arjun            NaT   False
5     Neha     2026-06-17    True
6    Rahul     2026-06-18   False
7    Kavya     2026-06-19    True
8    Vivek     2026-06-20   False
9    Meera     2026-06-21    True
10  Ishaan     2026-06-22    True
11   Anaya     2026-06-23   False

In [97]:
# Part E — Category Conversion
# 1. Convert Course to category dtype.
df_clean["Course"] = df_clean["Course"].astype("category")
df_clean["Course"]
# 2. Convert City to category dtype.
df_clean["City"] = df_clean["City"].astype("category")
df_clean["City"]
# 3. Display the categories available in Course and City.
print(df_clean["Course"])
print(df_clean["City"])
# 4. Explain why Course and City are better candidates for category than Student_ID.
# BEcause Student iD is mostly fall in the category of numbers but the city and Course are proper categoris and we can perform grouping on them but not on student ID

0        BCA
1        BCA
2     BSc IT
3        BCA
4        MCA
5     BSc IT
6        BCA
7        MCA
8        MCA
9     BSc IT
10       BCA
11       MCA
Name: Course, dtype: category
Categories (3, object): ['BCA', 'BSc IT', 'MCA']
0      Vadodara
1     Ahmedabad
2         Surat
3      Vadodara
4     Ahmedabad
5         Surat
6      Vadodara
7     Ahmedabad
8         Surat
9      Vadodara
10    Ahmedabad
11        Surat
Name: City, dtype: category
Categories (3, object): ['Ahmedabad', 'Surat', 'Vadodara']

In [ ]:
# Part F — Verification and Analysis
# 1. Display the final dtypes.
df_clean.dtypes
# 2. Count missing values created by failed conversions.
print(df_clean.isna().sum())

# 3. Display all rows containing a missing Age, Marks, orAdmission_Date after conversion. ( use ' | ' ) 
print(
    df_clean[
        df_clean["Age"].isna()
        | df_clean["Marks"].isna()
        | df_clean["Admission_Date"].isna()
    ]
)
# 4. Compare the raw and converted Marks columns and explain what errors='coerce' did.
print(df["Marks"])
print(df_clean["Marks"])

# Errors='coerce'->  converts invalid values (like trying to convert "abc" into a number ) into missing data
# 5. Save your converted DataFrame as your own CSV and compare it with the supplied clean dataset only after completing the practical.
df_clean.to_csv("case1_clean.csv", index=False)

Student_ID        0
Name              0
Age               2
Marks             2
Admission_Date    1
Hostel            0
Course            0
City              0
Semester          0
dtype: int64
  Student_ID   Name   Age  Marks Admission_Date  Hostel  Course       City  \
2       S003  Rohan  <NA>   78.0     2026-06-14    True  BSc IT      Surat
3       S004  Priya    19    NaN     2026-06-15    True     BCA   Vadodara
4       S005  Arjun    22   88.0            NaT   False     MCA  Ahmedabad
5       S006   Neha  <NA>   81.0     2026-06-17    True  BSc IT      Surat
8       S009  Vivek    22    NaN     2026-06-20   False     MCA      Surat

   Semester
2         2
3         5
4         4
5         3
8         4
0           85
1          92
2           78
3       Absent
4           88
5           81
6          67
7           95
8     84 marks
9           76
10          89
11          91
Name: Marks, dtype: object
0     85.0
1     92.0
2     78.0
3      NaN
4     88.0
5     81.0
6     67.0
7     95.0
8      NaN
9     76.0
10    89.0
11    91.0
Name: Marks, dtype: float64